### ISSUE TITLE
Error when scanning pst file

### ISSUE THREAD

**Issue by rb3p** [Dionach/PANhunt#18]
Hi there, 
I appear to be getting the following error when trying to scan a folder with pst file. Is there anything else required to be able to successfully scan a pst?

  File "pst.py", line 1185, in __init__
    class EntryID:
struct.error: unpack requires a string argument of length 24
Failed to execute script panhunt

Thanks :-)

**Comment by bli-dn** [comment]
You don't need anything else to scan a PST. Seems like a problem with the PST file.

**Comment by Chewie9999** [comment]
I have a similar error on one of my PSTs:
```
Traceback (most recent call last):                      | ETA:  --:--:-- PANs:0
  File "panhunt.py", line 251, in <module>
  File "panhunt.py", line 198, in hunt_pans
  File "filehunt.py", line 349, in find_all_regexs_in_psts
  File "filehunt.py", line 139, in check_pst_regexs
  File "pst.py", line 1989, in get_total_attachment_count
  File "pst.py", line 1924, in message_generator
  File "pst.py", line 1329, in __init__
  File "pst.py", line 1135, in get_pc_by_nid
  File "pst.py", line 905, in __init__
  File "pst.py", line 627, in __init__
  File "pst.py", line 762, in value
  File "pst.py", line 793, in get_multi_value_offsets
struct.error: unpack requires a string argument of length 8
Failed to execute script panhunt
```
If it is a problem with the file itself, can panhunt be amended so it will carry on if any errors occur?
It was running for several hours before it got to this file, and no results were saved to the OUTFILE.
Could output be saved at intervals so that the results are not lost in the event of a crash?

Thanks,
