### ISSUE TITLE
UnicodeDecodeError: 'utf16' codec can't decode bytes

### ISSUE THREAD

**Issue by Chewie9999** [Dionach/PANhunt#29]
When scanning a fileserver, it didn't like one of the .PST files:

```
Traceback (most recent call last):|                     | ETA:  --:--:-- PANs:0
  File "panhunt.py", line 251, in <module>
  File "panhunt.py", line 198, in hunt_pans
  File "filehunt.py", line 349, in find_all_regexs_in_psts
  File "filehunt.py", line 139, in check_pst_regexs
  File "pst.py", line 1989, in get_total_attachment_count
  File "pst.py", line 1924, in message_generator
  File "pst.py", line 1329, in __init__
  File "pst.py", line 1135, in get_pc_by_nid
  File "pst.py", line 905, in __init__
  File "pst.py", line 627, in __init__
  File "pst.py", line 707, in value
  File "encodings\utf_16_le.py", line 16, in decode
UnicodeDecodeError: 'utf16' codec can't decode bytes in position 508-509: unexpected end of data
Failed to execute script panhunt
```

Not quite sure why, could it be that the file changed during the scan?

**Comment by parteeksingh005** [comment]
When scanning a fileserver, I am getting a wired error. Attached for image for reference. 

![image (3)](https://user-images.githubusercontent.com/39644332/162883729-c8b3c26d-bb77-4305-a419-4daefddcec61.png)

Not quite sure why this happened..
