### ISSUE TITLE
Compiled Win exe won't run

### ISSUE THREAD

**Issue by mchristiana429** [Dionach/PANhunt#4]
I compiled the script as described and when I run the exe I get the following error:

Traceback (most recent call last):
  File "panhunt.py", line 251, in < module >
  File "panhunt.py", line 193, in hunt_pans
  File "filehunt.py", line 263, in find_all_files_in_directory
AttributeError: 'module' object has no attribute 'Percentage'
Failed to execute script panhunt

I have been unable to determine what the issue is.  This is an awesome tool that could be very useful for me.  I appreciate you sharing it and any help getting it to work if you can.  -Matt

**Comment by mchristiana429** [comment]
I think I have this resolved.   I am not sure I understand why, but I ran the panhunt.py script in python in Windows.  Doing so, I saw that it created some files as it ran.  After it ran successfully I tried compiling it again and now my EXE works.
